### ISSUE TITLE
Add arXiv data to database

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview-standup#45]

**Comment by dasaderi** [comment]
Update after call with WinGravity:

This is something that we should do only if we want to fix the issue of the search. See [issue #64](https://github.com/PREreview/prereview-standup/issues/64). Currently the arXiv data is not all in because it's huge and Rik did not finish importing it (as far as I understand).

**Comment by blahah** [comment]
The issue with ArXiv was that there are LaTeX characters in the metadata and I didn't find a nice solution for rendering them well. I have just seen this potential solution: https://github.com/PREreview/getpreprints/issues/6

**Comment by blahah** [comment]
If this was solved would you mind sharing the solution?
