### ISSUE TITLE
Issues with deployment

### ISSUE THREAD

**Issue by joehand** [PREreview/prereview-standup#69]
I noticed that v2.prereview.org was down again this morning. Upon investigation found a few things:

* It had been down for a few days.
* It was still being run in dev mode `npm run dev`, not with pm2 in production mode as discussed with Rik.
* `npm run start` [as documented](https://github.com/PREreview/dev-docs) doesn't work (starts but the homepage fails to load with a 404, more details below.)
* There is no `crontab`under the root user to restart the server daily as Rik said there was.

I've restarted in development mode (`npm run dev`) until we can fix the production script. I've also added an alert which should notify us before it crashes again.

**Comment by blahah** [comment]
@joehand apologies, there's an update to the `package.json` scripts, and the push failed without me noticing.

quickest fix (off the top of my head, without being able to test it), in the repo on the server:

```bash
cd client && npm run build
npm restart
```

**Comment by blahah** [comment]
The underlying issue there is that the client code needs rebuilding for production using the bankai scripts in the client `package.json`, and that should happen after every change in order for it to be reflected in production.
