### ISSUE TITLE
First time profile setting

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview-standup#70]
The way how a user has to select privacy right now is unintuitive and buggy. 

- [ ] Fix explanation of what private vs public means

- [ ] Redesign UX

- [ ] After your select, it does not register selection and asks  you to redo it.

- [ ] If you keep private it does not show what your public name will be. Make it so that it can be changed by user.

**Comment by blahah** [comment]
point #3 is fixed, and requires a rebuild of the production code

**Comment by dasaderi** [comment]
Update following call with WinGravity team:

PRE is written with https://choo.io/ . Rapid is written with React (and hooks).  For the current deadline of January 1st, Sebastien suggested to patch the PRE code by “just” fixing the CSS that is not responsive yet.

**Comment by wingravity** [comment]
Private vs Private - first priority
Redesign UX - I don’t like the 3 different quadrant thing for the biography - this is not a priority -
