### ISSUE TITLE
Import biography from ORCID profile 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview-standup#80]
I don't know if this is already implemented, but I'd like to import bio from ORCID if present.

**Comment by blahah** [comment]
This is already implemented.

**Comment by blahah** [comment]
Import on the server side (updated at every login): https://github.com/PREreview/prereview-standup/blob/master/server/auth/orcid/profile.js#L50-L75

Display on the client side: https://github.com/PREreview/prereview-standup/blob/master/client/components/profile/index.js#L134-L138
